//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.UserAccount = new HashSet<UserAccount>();
        }
    
        public int id { get; set; }
        public string identityCard { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string secondLastName { get; set; }
        public System.DateTime birthDate { get; set; }
        public string address { get; set; }
        public long phone { get; set; }
        public string position { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdAt { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccount> UserAccount { get; set; }
    }
}
