//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovement
    {
        public long id { get; set; }
        public int productId { get; set; }
        public string movementType { get; set; }
        public decimal quantity { get; set; }
        public string reference { get; set; }
        public System.DateTime date { get; set; }
        public string createdBy { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
